-- ADD FIELD
ALTER TABLE users ADD COLUMN jenis_kelamin VARCHAR(10);

-- RENAME FIELD
ALTER TABLE users RENAME COLUMN jenis_kelamin TO jk;

ALTER TABLE users CHANGE COLUMN jenis_kelamin jk VARCHAR(10);


-- modify
ALTER TABLE users MODIFY jk INT;

-- HAPUS
ALTER TABLE users DROP COLUMN jk;
-- ADD PRIMARI KEY DARI FIELD YG SUDAH ADA
ALTER TABLE nama_table modify id int PRIMARY KEY;
ALTER TABLE products ADD PRIMARY KEY (id);

-- ADD NILAI DEFAULT DARI FIELD YG SUDAH ADA
ALTER TABLE useraja modify phone VARCHAR(64) DEFAULT 0;

-- ADD AUTO_INCREMENT
ALTER TABLE useraja modify id INT AUTO_INCREMENT;

-- ADD FIELD UNTUK FOREIGN KEY
ALTER TABLE products ADD COLUMN id_category INT AFTER name;